'use client';
import {useEffect,useRef,useState} from 'react';
import {Smartphone,ExternalLink,RefreshCw,Check,AlertTriangle} from 'lucide-react';
import {probeFromDevice} from '../lib/browser-probe';
import {deviceLabel} from '../lib/diagnostic-summary';
export default function DeviceCheck({result,value,onChange}:{result:any;value:any;onChange:(value:any)=>void}){
 const control=useRef<AbortController|null>(null);const [loading,setLoading]=useState(false);const web=!result.kind||result.kind==='web';
 useEffect(()=>()=>{control.current?.abort()},[]);
 async function run(){control.current?.abort();const ctrl=new AbortController();control.current=ctrl;setLoading(true);try{const auto=await probeFromDevice(result.target,{signal:ctrl.signal,online:navigator.onLine});if(!ctrl.signal.aborted)onChange({...value,auto})}catch{}finally{if(!ctrl.signal.aborted)setLoading(false)}}
 function observed(outcome:string){control.current?.abort();setLoading(false);onChange({...value,manual:{outcome,at:new Date().toISOString()}})}
 const auto=value?.auto;
 return <section className="card device-check"><div className="card-title"><h3><Smartphone size={20}/>Depuis ton téléphone</h3><span className="pill">Ton réseau</span></div><p>{web?'Vérifie ton propre accès, puis confirme si la page s’ouvre vraiment.':'Ce service se vérifie dans son application, par exemple Minecraft ou un client SSH. Le navigateur ne peut pas tester directement ces connexions.'}</p>{web&&<div className="button-row"><button className="button primary" disabled={loading} onClick={run}><RefreshCw size={16} className={loading?'spin':''}/>{loading?'Vérification…':'Vérifier la réponse'}</button><a className="button secondary" href={result.target} target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/>Ouvrir le site</a></div>}
 {auto&&<div className={`device-observation ${auto.kind==='response'?'received':''}`} role="status">{auto.kind==='response'?<Check size={20}/>:<AlertTriangle size={20}/>}<div><strong>{auto.kind==='response'?'Une réponse est arrivée.':auto.kind==='unsupported'?'Ouvre le site pour vérifier.':auto.kind==='offline'?'Internet est nécessaire.':'Aucune réponse observable.'}</strong><p>{auto.kind==='response'?auto.status?`Le navigateur a reçu une réponse HTTP ${auto.status}. Vérifie la page en l’ouvrant.`:'Un serveur a répondu à cette requête. Le code, le contenu et les redirections sont masqués : cela ne garantit pas que la page fonctionne.':auto.reason}</p>{auto.kind==='unobserved'&&<p>Un délai, un certificat, un filtrage ou les règles du navigateur peuvent l’expliquer. Aucun blocage précis n’est confirmé.</p>}<small>{auto.ms!=null?`${auto.ms} ms · `:''}{new Date(auto.at).toLocaleTimeString('fr-FR')} · requête web HEAD, pas un ping</small></div></div>}
 <div className="manual-observation"><strong>{web?'Après avoir ouvert le site, qu’as-tu constaté ?':'Dans l’application du service, qu’as-tu constaté ?'}</strong><div className="observation-buttons"><button className={value?.manual?.outcome==='opens'?'selected':''} onClick={()=>observed('opens')}><Check size={16}/>{web?'La page s’ouvre':'Le service fonctionne'}</button><button className={value?.manual?.outcome==='fails'?'selected':''} onClick={()=>observed('fails')}>{web?'Elle ne s’ouvre pas':'Il ne fonctionne pas'}</button>{web&&<button className={value?.manual?.outcome==='certificate'?'selected':''} onClick={()=>observed('certificate')}>Alerte de sécurité</button>}</div>{value?.manual&&<p className="subnote">Enregistré comme ton observation, pas comme un test automatique. {new Date(value.manual.at).toLocaleString('fr-FR')} · <button className="text-button inline" onClick={()=>onChange({...value,manual:null})}>Effacer</button></p>}</div>
 {value&&<details><summary>Ce qui est enregistré</summary><p>{deviceLabel(value)}</p><p>Le test automatique demande uniquement une réponse, sans lire la page. Une erreur HTTP peut aussi produire une réponse. Ton observation indique séparément si le service fonctionne pour toi.</p></details>}
 </section>
}
