'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,Smartphone,X,Check} from 'lucide-react';
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>};
export default function InstallApp(){
 const [prompt,setPrompt]=useState<InstallEvent|null>(null),[installed,setInstalled]=useState(false),[platform,setPlatform]=useState('android'),[open,setOpen]=useState(false),[installing,setInstalling]=useState(false),[notice,setNotice]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const standalone=window.matchMedia('(display-mode: standalone)');setInstalled(standalone.matches||(navigator as Navigator&{standalone?:boolean}).standalone===true);setPlatform(/iPad|iPhone|iPod/.test(navigator.userAgent)?'ios':/Android/.test(navigator.userAgent)?'android':'desktop');
 const onPrompt=(event:Event)=>{event.preventDefault();setPrompt(event as InstallEvent)};const onInstalled=()=>{setInstalled(true);setPrompt(null);setOpen(false)};const onDisplay=()=>setInstalled(standalone.matches);
 window.addEventListener('beforeinstallprompt',onPrompt);window.addEventListener('appinstalled',onInstalled);standalone.addEventListener('change',onDisplay);
 if('serviceWorker' in navigator&&window.isSecureContext)navigator.serviceWorker.register('/sw.js',{scope:'/',updateViaCache:'none'}).then(reg=>reg.update()).catch(()=>setNotice('L’accès hors ligne n’a pas pu être préparé. Ouvre à nouveau l’application avec une connexion.'));
 return()=>{window.removeEventListener('beforeinstallprompt',onPrompt);window.removeEventListener('appinstalled',onInstalled);standalone.removeEventListener('change',onDisplay)};
 },[]);
 useEffect(()=>{if(open&&!dialog.current?.open)dialog.current?.showModal();else if(!open&&dialog.current?.open)dialog.current.close()},[open]);
 async function install(){if(!prompt){setOpen(true);return}setInstalling(true);setNotice('');try{await prompt.prompt();const choice=await prompt.userChoice;setPrompt(null);if(choice.outcome==='accepted'){setNotice('Installation demandée. Termine la confirmation de ton navigateur.');setOpen(true)}}catch{setPrompt(null);setOpen(true)}finally{setInstalling(false)}}
 return <><button type="button" className="install-button" onClick={()=>installed?setOpen(true):install()} disabled={installing}>{installed?<Check size={16}/>:<Download size={16}/>}<span>{installed?'Application':installing?'Installation…':'Installer'}</span></button><dialog ref={dialog} className="install-dialog" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)} aria-labelledby="install-title"><div className="card-title"><div className="install-mark"><Smartphone size={26}/></div><button className="icon-button" aria-label="Fermer" onClick={()=>setOpen(false)}><X size={20}/></button></div><h2 id="install-title">{installed?'Network Toolbox est installée':'Network Toolbox sur ton téléphone'}</h2><p>{installed?'Ouvre-la depuis son icône pour retrouver tes outils, captures et favoris.':'Retrouve tes outils directement depuis une icône, dans une fenêtre sans barre d’adresse.'}</p>{notice&&<p className="notice" role="status">{notice}</p>}{!installed&&(prompt?<button className="button primary full" onClick={install} disabled={installing}><Download size={18}/>Installer l’application</button>:<ol className="install-steps">{platform==='ios'?<><li>Ouvre ce site dans <strong>Safari</strong>.</li><li>Ouvre le menu <strong>Partager</strong>.</li><li>Choisis <strong>Sur l’écran d’accueil</strong>, puis confirme.</li></>:platform==='android'?<><li>Ouvre ce site dans <strong>Chrome</strong>, en dehors de ChatGPT.</li><li>Ouvre le menu <strong>⋮</strong> du navigateur.</li><li>Choisis <strong>Installer l’application</strong> ou <strong>Ajouter à l’écran d’accueil</strong>, puis confirme.</li></>:<><li>Ouvre ce site dans Chrome ou Edge.</li><li>Utilise l’icône d’installation de la barre d’adresse ou l’option d’installation du menu.</li><li>Sur téléphone, ouvre le même lien dans ton navigateur puis ajoute-le à l’écran d’accueil.</li></>}</ol>)}<div className="install-offline"><strong>Ce qui fonctionne hors ligne</strong><p>Les calculs et tes données enregistrées restent accessibles une fois l’application chargée en ligne. Les nouveaux diagnostics et les mesures réseau demandent Internet.</p></div><p className="subnote">Si ton navigateur propose uniquement un raccourci, le mode d’ouverture dépend de ce navigateur. Une connexion à ChatGPT peut être nécessaire au premier lancement de ce site privé.</p></dialog></>;
}
